### ISSUE TITLE
Claim?

### ISSUE THREAD

**Issue by Takeshi-Nakamoto** [btcking/btcking#1]
Bitcoin King does not make use of Segwit. With that being said, will users who held BTC on Segwit addresses be able to claim? Only available for Legacy address holders?

**Comment by douchebanner** [comment]
i have a non-segwit key and i cant claim anyway so...

the client doesnt seem to be syncing properly

**Comment by ymgve** [comment]
This is a scamcoin. Their chain is completely separate from BTC and is not a fork. Look at their genesis transaction: https://browser.btcking.org/insight/block/0a8eb4a7fb61600219c38a3f08b642f04469bd703b043ce7d4da39bf6a5708e3

Looking around on their block explorer, there have also been NO transactions on the chain at all, it's all mined coins. None of the addresses that had BTC on the claimed fork height have BTC in this chain. Scam.

**Comment by 0xbytes** [comment]
LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL 
SCAM ALERT - SCAM ALERT - SCAM ALERT - SCAM ALERT - SCAM ALERT 
all blocks have zero transactions
for example:
498000 - https://browser.btcking.org/insight/block/038c79200e31169ff485c2f498b7faf39abd75e84009b19ca3bd6a5e33086a90
498001 - https://browser.btcking.org/insight/block/0ab0e6a623d96355d6c1e9279e7a4d500c5adab6210bd569a13e42f92eae1a2e

**Comment by ymgve** [comment]
Actually looking closer, there are some transactions, like this one: https://browser.btcking.org/insight/block/00000000000000f81c7a806c25edff92a042b2dc9e004479aba12ba10189b6be

For some reason any block with transactions are simply not shown in the block overview.

(For extra WTFness, look at http://omnichest.info/lookupadd.aspx?address=1EmU2pxCFVuY6owWRQ8qHtxiCAzT2L39Tt - what is a Tether address doing in the BCK blockchain?)

I've gone through the whole blockchain now though, and it's clear there was no automatic airdrop or anything like that for BTC owners, so this is more like an altcoin than a fork.

**Comment by 0xbytes** [comment]
Transaction only show up after the fork. This means that "the btcking foundation" is claiming every coin up to block 500,000 which is 16,750,000 BCK
 
10,500,000   up to 210,000 block
 5,250,000   up to 420,000 block
 1,000,000   up to 500,000 block
==========
16,750,000

LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL LOL

**Comment by btcking0** [comment]
you can claim your coin by sending a encrypted message with your private key and your address to our support email,  we check your message and amount on 499999 block height and send BCK to you.

**Comment by fabrizioq83** [comment]
are you serious btcking0?? Our privatkey to your staff?? ahhahahahahahahhahahahahahahahhahahahaha

**Comment by btcking0** [comment]
@fabrizioq83 not private key. `a message` signed with your private key. message, message, message.

to proof you own the amount of BTC at 499999 height.

**Comment by btcking0** [comment]
@fabrizioq83 you are 抖机灵. 

maybe `a encrypted message with your private key` should be `a message encrypted with your private key`
